//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: file/netMessage.proto
namespace netMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M0001")]
  public partial class M0001 : global::ProtoBuf.IExtensible
  {
    public M0001() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M0002")]
  public partial class M0002 : global::ProtoBuf.IExtensible
  {
    public M0002() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M0003")]
  public partial class M0003 : global::ProtoBuf.IExtensible
  {
    public M0003() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M0004")]
  public partial class M0004 : global::ProtoBuf.IExtensible
  {
    public M0004() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M0005")]
  public partial class M0005 : global::ProtoBuf.IExtensible
  {
    public M0005() {}
    
    private string _gender;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private string _job;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string job
    {
      get { return _job; }
      set { _job = value; }
    }
    private string _age;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"age", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string age
    {
      get { return _age; }
      set { _age = value; }
    }
    private string _interest;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"interest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string interest
    {
      get { return _interest; }
      set { _interest = value; }
    }
    private string _roleName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M0006")]
  public partial class M0006 : global::ProtoBuf.IExtensible
  {
    public M0006() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M0007")]
  public partial class M0007 : global::ProtoBuf.IExtensible
  {
    public M0007() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M0008")]
  public partial class M0008 : global::ProtoBuf.IExtensible
  {
    public M0008() {}
    
    private string _info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M0010")]
  public partial class M0010 : global::ProtoBuf.IExtensible
  {
    public M0010() {}
    
    private string _info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M0011")]
  public partial class M0011 : global::ProtoBuf.IExtensible
  {
    public M0011() {}
    
    private string _fileName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fileName
    {
      get { return _fileName; }
      set { _fileName = value; }
    }
    private string _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _crc;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"crc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string crc
    {
      get { return _crc; }
      set { _crc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M0012")]
  public partial class M0012 : global::ProtoBuf.IExtensible
  {
    public M0012() {}
    
    private string _fileName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fileName
    {
      get { return _fileName; }
      set { _fileName = value; }
    }
    private string _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _info;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string info
    {
      get { return _info; }
      set { _info = value; }
    }
    private string _fileSrc = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fileSrc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fileSrc
    {
      get { return _fileSrc; }
      set { _fileSrc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M0013")]
  public partial class M0013 : global::ProtoBuf.IExtensible
  {
    public M0013() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M0014")]
  public partial class M0014 : global::ProtoBuf.IExtensible
  {
    public M0014() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"theScript")]
  public partial class theScript : global::ProtoBuf.IExtensible
  {
    public theScript() {}
    
    private string _fileName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fileName
    {
      get { return _fileName; }
      set { _fileName = value; }
    }
    private string _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _crc;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"crc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string crc
    {
      get { return _crc; }
      set { _crc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M0015")]
  public partial class M0015 : global::ProtoBuf.IExtensible
  {
    public M0015() {}
    
    private readonly global::System.Collections.Generic.List<netMessage.theScript> _datas = new global::System.Collections.Generic.List<netMessage.theScript>();
    [global::ProtoBuf.ProtoMember(1, Name=@"datas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<netMessage.theScript> datas
    {
      get { return _datas; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"scriptRet")]
  public partial class scriptRet : global::ProtoBuf.IExtensible
  {
    public scriptRet() {}
    
    private string _fileName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fileName
    {
      get { return _fileName; }
      set { _fileName = value; }
    }
    private string _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _info = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string info
    {
      get { return _info; }
      set { _info = value; }
    }
    private string _fileSrc = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fileSrc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fileSrc
    {
      get { return _fileSrc; }
      set { _fileSrc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M0016")]
  public partial class M0016 : global::ProtoBuf.IExtensible
  {
    public M0016() {}
    
    private readonly global::System.Collections.Generic.List<netMessage.scriptRet> _datas = new global::System.Collections.Generic.List<netMessage.scriptRet>();
    [global::ProtoBuf.ProtoMember(1, Name=@"datas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<netMessage.scriptRet> datas
    {
      get { return _datas; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1000")]
  public partial class M1000 : global::ProtoBuf.IExtensible
  {
    public M1000() {}
    
    private string _info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1001")]
  public partial class M1001 : global::ProtoBuf.IExtensible
  {
    public M1001() {}
    
    private string _info = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1002")]
  public partial class M1002 : global::ProtoBuf.IExtensible
  {
    public M1002() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1003")]
  public partial class M1003 : global::ProtoBuf.IExtensible
  {
    public M1003() {}
    
    private string _roleName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }
    private string _age;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"age", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string age
    {
      get { return _age; }
      set { _age = value; }
    }
    private string _gender;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private string _organ;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"organ", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string organ
    {
      get { return _organ; }
      set { _organ = value; }
    }
    private string _onlineDays;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"onlineDays", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string onlineDays
    {
      get { return _onlineDays; }
      set { _onlineDays = value; }
    }
    private string _healthpoint;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"healthpoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string healthpoint
    {
      get { return _healthpoint; }
      set { _healthpoint = value; }
    }
    private string _stamina;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"stamina", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string stamina
    {
      get { return _stamina; }
      set { _stamina = value; }
    }
    private string _city;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"city", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string city
    {
      get { return _city; }
      set { _city = value; }
    }
    private float _posX;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posX
    {
      get { return _posX; }
      set { _posX = value; }
    }
    private float _posY;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posY
    {
      get { return _posY; }
      set { _posY = value; }
    }
    private float _posZ;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"posZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posZ
    {
      get { return _posZ; }
      set { _posZ = value; }
    }
    private string _posId;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1004")]
  public partial class M1004 : global::ProtoBuf.IExtensible
  {
    public M1004() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemInfo")]
  public partial class ItemInfo : global::ProtoBuf.IExtensible
  {
    public ItemInfo() {}
    
    private string _typeId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"typeId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string typeId
    {
      get { return _typeId; }
      set { _typeId = value; }
    }
    private string _guid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private int _equiped = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"equiped", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equiped
    {
      get { return _equiped; }
      set { _equiped = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1005")]
  public partial class M1005 : global::ProtoBuf.IExtensible
  {
    public M1005() {}
    
    private string _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<netMessage.ItemInfo> _itemList = new global::System.Collections.Generic.List<netMessage.ItemInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"itemList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<netMessage.ItemInfo> itemList
    {
      get { return _itemList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1006")]
  public partial class M1006 : global::ProtoBuf.IExtensible
  {
    public M1006() {}
    
    private string _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _op;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"op", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string op
    {
      get { return _op; }
      set { _op = value; }
    }
    private netMessage.ItemInfo _item;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public netMessage.ItemInfo item
    {
      get { return _item; }
      set { _item = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1007")]
  public partial class M1007 : global::ProtoBuf.IExtensible
  {
    public M1007() {}
    
    private string _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private readonly global::System.Collections.Generic.List<netMessage.M1007.Operation> _param = new global::System.Collections.Generic.List<netMessage.M1007.Operation>();
    [global::ProtoBuf.ProtoMember(2, Name=@"param", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<netMessage.M1007.Operation> param
    {
      get { return _param; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Operation")]
  public partial class Operation : global::ProtoBuf.IExtensible
  {
    public Operation() {}
    
    private string _op;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"op", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string op
    {
      get { return _op; }
      set { _op = value; }
    }
    private string _tag = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tag
    {
      get { return _tag; }
      set { _tag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1008")]
  public partial class M1008 : global::ProtoBuf.IExtensible
  {
    public M1008() {}
    
    private string _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _guid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private int _count = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private string _from = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"from", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string from
    {
      get { return _from; }
      set { _from = value; }
    }
    private string _to = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"to", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string to
    {
      get { return _to; }
      set { _to = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"skillNormal")]
  public partial class skillNormal : global::ProtoBuf.IExtensible
  {
    public skillNormal() {}
    
    private string _typeId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"typeId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string typeId
    {
      get { return _typeId; }
      set { _typeId = value; }
    }
    private int _current;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"current", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int current
    {
      get { return _current; }
      set { _current = value; }
    }
    private int _max;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"max", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int max
    {
      get { return _max; }
      set { _max = value; }
    }
    private int _limit;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int limit
    {
      get { return _limit; }
      set { _limit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1009")]
  public partial class M1009 : global::ProtoBuf.IExtensible
  {
    public M1009() {}
    
    private readonly global::System.Collections.Generic.List<netMessage.skillNormal> _skillList = new global::System.Collections.Generic.List<netMessage.skillNormal>();
    [global::ProtoBuf.ProtoMember(1, Name=@"skillList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<netMessage.skillNormal> skillList
    {
      get { return _skillList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"skillFeature")]
  public partial class skillFeature : global::ProtoBuf.IExtensible
  {
    public skillFeature() {}
    
    private string _typeId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"typeId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string typeId
    {
      get { return _typeId; }
      set { _typeId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1023")]
  public partial class M1023 : global::ProtoBuf.IExtensible
  {
    public M1023() {}
    
    private readonly global::System.Collections.Generic.List<netMessage.skillFeature> _skillList = new global::System.Collections.Generic.List<netMessage.skillFeature>();
    [global::ProtoBuf.ProtoMember(1, Name=@"skillList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<netMessage.skillFeature> skillList
    {
      get { return _skillList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1010")]
  public partial class M1010 : global::ProtoBuf.IExtensible
  {
    public M1010() {}
    
    private netMessage.skillNormal _info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public netMessage.skillNormal info
    {
      get { return _info; }
      set { _info = value; }
    }
    private string _notify = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"notify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string notify
    {
      get { return _notify; }
      set { _notify = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"taskData")]
  public partial class taskData : global::ProtoBuf.IExtensible
  {
    public taskData() {}
    
    private string _taskId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"taskId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string taskId
    {
      get { return _taskId; }
      set { _taskId = value; }
    }
    private string _endTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private string _time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1011")]
  public partial class M1011 : global::ProtoBuf.IExtensible
  {
    public M1011() {}
    
    private readonly global::System.Collections.Generic.List<netMessage.taskData> _taskList = new global::System.Collections.Generic.List<netMessage.taskData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"taskList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<netMessage.taskData> taskList
    {
      get { return _taskList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1012")]
  public partial class M1012 : global::ProtoBuf.IExtensible
  {
    public M1012() {}
    
    private string _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _src = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"src", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string src
    {
      get { return _src; }
      set { _src = value; }
    }
    private string _notify = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"notify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string notify
    {
      get { return _notify; }
      set { _notify = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"mapElement")]
  public partial class mapElement : global::ProtoBuf.IExtensible
  {
    public mapElement() {}
    
    private string _typeId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"typeId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string typeId
    {
      get { return _typeId; }
      set { _typeId = value; }
    }
    private string _posId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private string _scriptName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"scriptName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string scriptName
    {
      get { return _scriptName; }
      set { _scriptName = value; }
    }
    private string _guid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private float _posX;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posX
    {
      get { return _posX; }
      set { _posX = value; }
    }
    private float _posZ;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"posZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posZ
    {
      get { return _posZ; }
      set { _posZ = value; }
    }
    private string _timeCur;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"timeCur", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string timeCur
    {
      get { return _timeCur; }
      set { _timeCur = value; }
    }
    private string _timeLimit;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"timeLimit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string timeLimit
    {
      get { return _timeLimit; }
      set { _timeLimit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1013")]
  public partial class M1013 : global::ProtoBuf.IExtensible
  {
    public M1013() {}
    
    private readonly global::System.Collections.Generic.List<netMessage.mapElement> _datas = new global::System.Collections.Generic.List<netMessage.mapElement>();
    [global::ProtoBuf.ProtoMember(1, Name=@"datas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<netMessage.mapElement> datas
    {
      get { return _datas; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1014")]
  public partial class M1014 : global::ProtoBuf.IExtensible
  {
    public M1014() {}
    
    private string _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private netMessage.mapElement _data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public netMessage.mapElement data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1015")]
  public partial class M1015 : global::ProtoBuf.IExtensible
  {
    public M1015() {}
    
    private string _posId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1022")]
  public partial class M1022 : global::ProtoBuf.IExtensible
  {
    public M1022() {}
    
    private string _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _posId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private float _posX = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float posX
    {
      get { return _posX; }
      set { _posX = value; }
    }
    private float _posZ = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"posZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float posZ
    {
      get { return _posZ; }
      set { _posZ = value; }
    }
    private string _stamina = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"stamina", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stamina
    {
      get { return _stamina; }
      set { _stamina = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1016")]
  public partial class M1016 : global::ProtoBuf.IExtensible
  {
    public M1016() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"searchInfo")]
  public partial class searchInfo : global::ProtoBuf.IExtensible
  {
    public searchInfo() {}
    
    private string _typeId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"typeId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string typeId
    {
      get { return _typeId; }
      set { _typeId = value; }
    }
    private string _posId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private string _scriptName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"scriptName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string scriptName
    {
      get { return _scriptName; }
      set { _scriptName = value; }
    }
    private string _guid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private float _posX;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posX
    {
      get { return _posX; }
      set { _posX = value; }
    }
    private float _posZ;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"posZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posZ
    {
      get { return _posZ; }
      set { _posZ = value; }
    }
    private string _timeCur;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"timeCur", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string timeCur
    {
      get { return _timeCur; }
      set { _timeCur = value; }
    }
    private string _timeLimit;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"timeLimit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string timeLimit
    {
      get { return _timeLimit; }
      set { _timeLimit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1017")]
  public partial class M1017 : global::ProtoBuf.IExtensible
  {
    public M1017() {}
    
    private readonly global::System.Collections.Generic.List<netMessage.searchInfo> _searchList = new global::System.Collections.Generic.List<netMessage.searchInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"searchList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<netMessage.searchInfo> searchList
    {
      get { return _searchList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"operateData")]
  public partial class operateData : global::ProtoBuf.IExtensible
  {
    public operateData() {}
    
    private int _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private string _operate;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"operate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string operate
    {
      get { return _operate; }
      set { _operate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1018")]
  public partial class M1018 : global::ProtoBuf.IExtensible
  {
    public M1018() {}
    
    private string _file;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"file", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string file
    {
      get { return _file; }
      set { _file = value; }
    }
    private readonly global::System.Collections.Generic.List<netMessage.operateData> _operateList = new global::System.Collections.Generic.List<netMessage.operateData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"operateList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<netMessage.operateData> operateList
    {
      get { return _operateList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1019")]
  public partial class M1019 : global::ProtoBuf.IExtensible
  {
    public M1019() {}
    
    private string _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"itemData")]
  public partial class itemData : global::ProtoBuf.IExtensible
  {
    public itemData() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _operate;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"operate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string operate
    {
      get { return _operate; }
      set { _operate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1020")]
  public partial class M1020 : global::ProtoBuf.IExtensible
  {
    public M1020() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<netMessage.itemData> _itemList = new global::System.Collections.Generic.List<netMessage.itemData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"itemList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<netMessage.itemData> itemList
    {
      get { return _itemList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1021")]
  public partial class M1021 : global::ProtoBuf.IExtensible
  {
    public M1021() {}
    
    private string _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1025")]
  public partial class M1025 : global::ProtoBuf.IExtensible
  {
    public M1025() {}
    
    private string _msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"M1024")]
  public partial class M1024 : global::ProtoBuf.IExtensible
  {
    public M1024() {}
    
    private string _msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}